[package]
name = "practice3_rs"
version = "0.1.0"
authors = ["sudachi0114 <jnevariste@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
